### ISSUE TITLE
타입에 오타가 있습니다

### ISSUE THREAD

**Issue by RanolP** [solved-ac/ui-react#16]
#5 (fix: invalid return type of cssVariables function)에서 적용한 타입에 오타가 있습니다. 실수로 고치다가 뒤에 있던 중괄호 하나를 그대로 놔뒀나봅니다. 🤯

https://github.com/solved-ac/ui-react/blob/7b3e77b2c4c84cf9dab02a587abc7c528dd5ffbf/src/utils/styles.ts#L40

https://github.com/solved-ac/ui-react/blob/7b3e77b2c4c84cf9dab02a587abc7c528dd5ffbf/src/utils/styles.ts#L54

**Comment by shiftpsh** [comment]
이슈 남겨 주셔서 감사합니다! 확인이 늦어서 죄송합니다. 다음 릴리즈 전에 수정하도록 하겠습니다.

**Comment by shiftpsh** [comment]
다시 확인해 봤는데 extra `}`가 있는 게 맞는지요? template string literal 문법인 걸로 보입니다.
