### ISSUE TITLE
solved-ac (번역 오류), 설정 > 계정 > Twitter 연동 > Twitter로 로그인 버튼

### ISSUE THREAD

**Issue by fing9** [solved-ac/ui-react#45]
**'설정' - '계정' - 'Twitter 연동' 에서 "Twitter로 로그인" 버튼**이
브라우저 언어가 Korean일 때와 English일 때 둘 다 Korean으로 표시되는 이슈가 있습니다.

사용 브라우저 : Arc, Safari
이슈 시연 일시 : 23.05.02 11:27

**[Korean]**
<img width="779" alt="스크린샷 2023-05-02 오전 11 27 24" src="https://user-images.githubusercontent.com/44383895/235566531-a8ec2bcc-156b-4be3-bf50-48c4eefc15c4.png">

**[English]**
<img width="674" alt="스크린샷 2023-05-02 오전 11 27 31" src="https://user-images.githubusercontent.com/44383895/235566517-199586fb-f252-4946-ae0d-dd7186e3bd3b.png">

**Comment by shiftpsh** [comment]
안녕하세요, 이슈를 남겨 주셔서 감사합니다.

이곳은 solved.ac의 UI 컴포넌트 라이브러리에 관한 이슈를 남기는 곳이며, solved.ac 서비스 관련 이슈는 shift@solved.ac로 보내주시면 감사하겠습니다.

UI 컴포넌트 라이브러리에 관한 이슈가 아니므로 이 이슈는 닫겠습니다. 별개로 번역 누락은 곧 수정하도록 하겠습니다.
